#!/usr/bin/env bash
# Regenerate THIRD-PARTY-NOTICES.txt from the ACTUAL dependency graph.
#
# openrate redistributes third-party code two ways: Go modules compiled into
# the binary, and browser assets vendored (as committed files, not npm
# packages) into the static marketing site under site/assets/ — the Geist
# Sans / Geist Mono webfonts (site/assets/fonts/, SIL OFL-1.1) and the
# highlight.js/marked bundles (site/assets/vendor/, each with its own
# .LICENSE file next to it). The embedded UI (web/ui.html) is a single
# hand-written HTML document with no npm dependency of any kind, so there is
# no npm dependency graph to resolve here any more. MIT, BSD, ISC,
# Apache-2.0 and OFL-1.1 all require the copyright notice and licence text to
# travel with the copy.
#
#     ./scripts/gen-notices.sh
#
# The generated file is committed, and copied to two places that must stay
# byte-identical to it: site/licenses.txt for the static marketing site, and
# web/THIRD-PARTY-NOTICES.txt, a physical copy inside web/ (go:embed patterns
# cannot contain "..", so the root file can't be embedded directly) that
# web/embed.go embeds as web.Licenses and Handler() serves at /licenses.txt.
# web/embed_test.go's TestLicensesInSyncWithRoot fails go test ./web if that
# copy ever drifts from the root file — this script is what keeps them in
# step. It is NOT hand-maintained.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

OUT="THIRD-PARTY-NOTICES.txt"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# --- Go modules: Elastic's go-licence-detector walks the real module graph and
# reproduces each module's licence text from the module cache.
DETECTOR="$(command -v go-licence-detector || true)"
if [[ -z "$DETECTOR" ]]; then
  echo "==> installing go.elastic.co/go-licence-detector@v0.10.0"
  GOBIN="$TMP/bin" go install go.elastic.co/go-licence-detector@v0.10.0
  DETECTOR="$TMP/bin/go-licence-detector"
fi

echo "==> resolving Go module graph"
go mod download
go list -m -json all | "$DETECTOR" \
  -includeIndirect \
  -noticeTemplate scripts/notices/go-modules.tmpl \
  -noticeOut "$TMP/go-notices.txt"

echo "==> composing $OUT"
{
  cat <<'HEADER'
================================================================================
openrate — THIRD-PARTY NOTICES
================================================================================

This file is generated by scripts/gen-notices.sh from the actual dependency
graph. Do not edit it by hand.

openrate is distributed under the MIT licence (see LICENSE). It bundles the
third-party software listed below. Each entry gives the component name, its
version, the licence it is distributed under, and the full text of that licence,
as those licences require. This file exists in three places, kept identical by
scripts/gen-notices.sh: here at the repo root; as site/licenses.txt, served by
the static marketing site at /licenses.txt; and as web/THIRD-PARTY-NOTICES.txt,
embedded into the openrate binary (web.Licenses) and served by it at
/licenses.txt too.

HEADER

  echo "================================================================================"
  echo "Vendored webfonts (marketing site, site/assets/fonts/)"
  echo "================================================================================"
  echo
  echo "Geist Sans and Geist Mono are shipped as .woff2 files directly under"
  echo "site/assets/fonts/ (committed files, no package manager involved) for the"
  echo "marketing site. The SIL Open Font License 1.1 requires this notice and"
  echo "licence text to accompany every redistribution of those font files. The"
  echo "embedded UI (web/ui.html) ships no webfonts at all — system font stacks only."
  echo
  for lic in site/assets/fonts/LICENSE-*.txt; do
    [[ -e "$lic" ]] || continue
    base="$(basename "$lic")"
    family="${base#LICENSE-}"
    family="${family%.txt}"
    files="$(ls site/assets/fonts/"${family}"-*.woff2 2>/dev/null | xargs -n1 basename | paste -sd ', ' -)"
    echo "--------------------------------------------------------------------------------"
    echo "Component : ${family}"
    echo "Licence   : SIL Open Font License 1.1"
    echo "Files     : ${files:-none found}"
    echo "--------------------------------------------------------------------------------"
    echo
    cat "$lic"
    echo
  done

  echo "================================================================================"
  echo "Vendored browser assets (marketing site, site/assets/vendor/)"
  echo "================================================================================"
  echo
  for lic in site/assets/vendor/*.LICENSE; do
    [[ -e "$lic" ]] || continue
    echo "--------------------------------------------------------------------------------"
    cat "$lic"
    echo
  done

  echo "================================================================================"
  echo "Go standard library (compiled into the openrate binary)"
  echo "================================================================================"
  echo
  echo "--------------------------------------------------------------------------------"
  echo "Component : The Go Programming Language standard library"
  echo "Version   : $(go env GOVERSION)"
  echo "Licence   : BSD-3-Clause (plus the Go patent grant, reproduced below)"
  echo "--------------------------------------------------------------------------------"
  echo
  cat "$(go env GOROOT)/LICENSE"
  echo
  cat "$(go env GOROOT)/PATENTS"
  echo

  echo "================================================================================"
  echo "Go modules (compiled into the openrate binary)"
  echo "================================================================================"
  echo
  if grep -q "^Module  :" "$TMP/go-notices.txt"; then
    cat "$TMP/go-notices.txt"
  else
    echo "None. openrate's Go code depends only on the Go standard library"
    echo "(see the section above); go.mod declares no module requirements."
    echo
  fi
} > "$OUT"

# Surface it. The static marketing site is deployed separately from the
# binary, so it gets its own copy at site/licenses.txt. web/THIRD-PARTY-NOTICES.txt
# is a physical copy too (go:embed patterns cannot contain "..", so web/ can't
# embed the root file directly) — web/embed.go embeds it as web.Licenses and
# serves it from the running binary at /licenses.txt. Regenerating notices
# without this copy would leave the embedded copy stale, which
# web/embed_test.go's TestLicensesInSyncWithRoot would then (correctly) catch.
cp "$OUT" site/licenses.txt
cp "$OUT" web/THIRD-PARTY-NOTICES.txt

echo "==> wrote $OUT, site/licenses.txt and web/THIRD-PARTY-NOTICES.txt ($(wc -l < "$OUT" | tr -d ' ') lines)"
