#!/usr/bin/env bash
# Regenerate THIRD-PARTY-NOTICES.txt from the ACTUAL dependency graph.
#
# openrate redistributes third-party code three ways: Go modules compiled into
# the binary, npm packages bundled into the embedded React app (including the
# Inter / JetBrains Mono webfonts, whose OFL-1.1 licence must accompany every
# copy of the .woff2 files), and the mermaid/marked bundles vendored into the
# marketing site. MIT, BSD, ISC, Apache-2.0 and OFL-1.1 all require the
# copyright notice and licence text to travel with the copy.
#
#     ./scripts/gen-notices.sh
#
# The generated file is committed (go:embed needs it at build time), served by
# the binary at /licenses.txt, and copied to site/licenses.txt for the static
# marketing site. It is NOT hand-maintained.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

OUT="THIRD-PARTY-NOTICES.txt"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# --- Go modules: Elastic's go-licence-detector walks the real module graph and
# reproduces each module's licence text from the module cache.
DETECTOR="$(command -v go-licence-detector || true)"
if [[ -z "$DETECTOR" ]]; then
  echo "==> installing go.elastic.co/go-licence-detector@v0.10.0"
  GOBIN="$TMP/bin" go install go.elastic.co/go-licence-detector@v0.10.0
  DETECTOR="$TMP/bin/go-licence-detector"
fi

echo "==> resolving Go module graph"
go mod download
go list -m -json all | "$DETECTOR" \
  -includeIndirect \
  -noticeTemplate scripts/notices/go-modules.tmpl \
  -noticeOut "$TMP/go-notices.txt"

# --- npm packages actually bundled into web/dist (production deps only).
echo "==> resolving npm dependency graph (web/)"
[[ -d web/node_modules ]] || (cd web && npm ci)
(cd web && npx --yes license-checker-rseidelsohn \
  --production --json --excludePrivatePackages --start .) \
  | node scripts/notices/npm-notices.mjs > "$TMP/npm-notices.txt"

echo "==> composing $OUT"
{
  cat <<'HEADER'
================================================================================
openrate — THIRD-PARTY NOTICES
================================================================================

This file is generated by scripts/gen-notices.sh from the actual dependency
graph. Do not edit it by hand.

openrate is distributed under the MIT licence (see LICENSE). It bundles the
third-party software listed below. Each entry gives the component name, its
version, the licence it is distributed under, and the full text of that licence,
as those licences require. The openrate binary serves this file at
/licenses.txt; the marketing site serves it at /licenses.txt too.

HEADER

  echo "================================================================================"
  echo "npm packages (bundled into the web UI served from the binary)"
  echo "================================================================================"
  echo
  echo "The Inter and JetBrains Mono webfonts below are shipped as .woff2 files in"
  echo "web/dist/assets/. SIL Open Font License 1.1 requires this notice and licence"
  echo "to accompany every redistribution of those font files."
  echo
  cat "$TMP/npm-notices.txt"

  echo "================================================================================"
  echo "Vendored browser assets (marketing site, site/assets/vendor/)"
  echo "================================================================================"
  echo
  for lic in site/assets/vendor/*.LICENSE; do
    [[ -e "$lic" ]] || continue
    echo "--------------------------------------------------------------------------------"
    cat "$lic"
    echo
  done

  echo "================================================================================"
  echo "Go standard library (compiled into the openrate binary)"
  echo "================================================================================"
  echo
  echo "--------------------------------------------------------------------------------"
  echo "Component : The Go Programming Language standard library"
  echo "Version   : $(go env GOVERSION)"
  echo "Licence   : BSD-3-Clause (plus the Go patent grant, reproduced below)"
  echo "--------------------------------------------------------------------------------"
  echo
  cat "$(go env GOROOT)/LICENSE"
  echo
  cat "$(go env GOROOT)/PATENTS"
  echo

  echo "================================================================================"
  echo "Go modules (compiled into the openrate binary)"
  echo "================================================================================"
  echo
  if grep -q "^Module  :" "$TMP/go-notices.txt"; then
    cat "$TMP/go-notices.txt"
  else
    echo "None. openrate's Go code depends only on the Go standard library"
    echo "(see the section above); go.mod declares no module requirements."
    echo
  fi
} > "$OUT"

# Surface it. web/public/ is copied verbatim into web/dist/ by Vite, and
# web/dist is embedded in the binary, so the notices end up served at
# /licenses.txt by any running openrate. The static marketing site is deployed
# separately, so it gets its own copy.
cp "$OUT" web/public/licenses.txt
cp "$OUT" site/licenses.txt

echo "==> rebuilding web/dist so the committed bundle carries the notices"
(cd web && npm run build >/dev/null)

echo "==> wrote $OUT, web/public/licenses.txt, web/dist/licenses.txt, site/licenses.txt ($(wc -l < "$OUT" | tr -d ' ') lines)"
