// Display metadata for the currencies openrate carries: full name + a flag/glyph
// so the dropdowns read clearly. Codes not listed fall back to the code itself.
export const CCY = {
  USD: { name: "US Dollar", flag: "🇺🇸" },
  EUR: { name: "Euro", flag: "🇪🇺" },
  GBP: { name: "British Pound", flag: "🇬🇧" },
  JPY: { name: "Japanese Yen", flag: "🇯🇵" },
  ZAR: { name: "South African Rand", flag: "🇿🇦" },
  AUD: { name: "Australian Dollar", flag: "🇦🇺" },
  CAD: { name: "Canadian Dollar", flag: "🇨🇦" },
  CHF: { name: "Swiss Franc", flag: "🇨🇭" },
  CNY: { name: "Chinese Yuan", flag: "🇨🇳" },
  HKD: { name: "Hong Kong Dollar", flag: "🇭🇰" },
  SGD: { name: "Singapore Dollar", flag: "🇸🇬" },
  INR: { name: "Indian Rupee", flag: "🇮🇳" },
  KRW: { name: "South Korean Won", flag: "🇰🇷" },
  BRL: { name: "Brazilian Real", flag: "🇧🇷" },
  MXN: { name: "Mexican Peso", flag: "🇲🇽" },
  NZD: { name: "New Zealand Dollar", flag: "🇳🇿" },
  SEK: { name: "Swedish Krona", flag: "🇸🇪" },
  NOK: { name: "Norwegian Krone", flag: "🇳🇴" },
  DKK: { name: "Danish Krone", flag: "🇩🇰" },
  PLN: { name: "Polish Złoty", flag: "🇵🇱" },
  CZK: { name: "Czech Koruna", flag: "🇨🇿" },
  HUF: { name: "Hungarian Forint", flag: "🇭🇺" },
  RON: { name: "Romanian Leu", flag: "🇷🇴" },
  BGN: { name: "Bulgarian Lev", flag: "🇧🇬" },
  ISK: { name: "Icelandic Króna", flag: "🇮🇸" },
  TRY: { name: "Turkish Lira", flag: "🇹🇷" },
  ILS: { name: "Israeli Shekel", flag: "🇮🇱" },
  IDR: { name: "Indonesian Rupiah", flag: "🇮🇩" },
  MYR: { name: "Malaysian Ringgit", flag: "🇲🇾" },
  PHP: { name: "Philippine Peso", flag: "🇵🇭" },
  THB: { name: "Thai Baht", flag: "🇹🇭" },
  AED: { name: "UAE Dirham", flag: "🇦🇪" },
  SAR: { name: "Saudi Riyal", flag: "🇸🇦" },
  NGN: { name: "Nigerian Naira", flag: "🇳🇬" },
  KES: { name: "Kenyan Shilling", flag: "🇰🇪" },
  GHS: { name: "Ghanaian Cedi", flag: "🇬🇭" },
  EGP: { name: "Egyptian Pound", flag: "🇪🇬" },
  MAD: { name: "Moroccan Dirham", flag: "🇲🇦" },
  BWP: { name: "Botswana Pula", flag: "🇧🇼" },
  BTC: { name: "Bitcoin", flag: "₿" },
  ETH: { name: "Ethereum", flag: "Ξ" },
  USDT: { name: "Tether", flag: "₮" },
  USDC: { name: "USD Coin", flag: "$" },
};

export function ccyName(code) { return CCY[code]?.name || code; }
export function ccyFlag(code) { return CCY[code]?.flag || "¤"; }
